name: main32

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          location: D:\
          install: >-
            zip
            p7zip
            git
            svn
            mingw-w64-ucrt-x86_64-texlive-core

      - name: Prepare and build core
        shell: msys2 {0}
        run: |
          ## Files Downloading
          wget -q https://archives.boost.io/release/1.86.0/source/boost_1_86_0.7z
          wget -q https://github.com/zxunge/build-wxWidgets/releases/download/wxWidgets-3.2.6-23-stl-shared-cb-winlibs1420/wxWidgets-3.2.6-23-stl-shared-cb-winlibs1420.7z
          wget -q https://sourceforge.net/projects/codeblocks/files/Binaries/Nightlies/Prerequisites/Mingw64dlls14.1.0.7z
          wget -q https://sourceforge.net/projects/codeblocks/files/Binaries/Nightlies/2024/CB_20240815_rev13542_win64.7z
          wget -q https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-18.1.8-12.0.0-ucrt-r1/winlibs-i686-posix-dwarf-gcc-14.2.0-mingw-w64ucrt-12.0.0-r1.7z
          wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.6/wxWidgets-3.2.6-headers.7z
          wget -q https://sourceforge.net/projects/codeblocks/files/Binaries/Nightlies/Prerequisites/wxmsw32u_gcc_cb_wx325_2D_gcc1410-mingw64.7z
          7z x ./Mingw64dlls14.1.0.7z -o/opt/codeblocks/bin
          7z x ./wxWidgets-3.2.6-headers.7z -o/opt/wxwidgets3.2
          7z x ./winlibs-i686-posix-dwarf-gcc-14.2.0-mingw-w64ucrt-12.0.0-r1.7z -o/opt
          7z x ./wxmsw32u_gcc_cb_wx325_2D_gcc1410-mingw64.7z -o/opt/codeblocks/bin
          7z x ./CB_20240815_rev13542_win64.7z -o/opt/codeblocks/bin
          7z x ./wxWidgets-3.2.6-23-stl-shared-cb-winlibs1420.7z -o/opt/wxwidgets3.2
          7z x ./boost_1_86_0.7z -o/opt
          git clone https://github.com/arnholm/codeblocks_sfmirror.git
          svn checkout https://svn.code.sf.net/p/fortranproject/code/trunk FortranProject

          cp /ucrt64/bin/repstopdf.exe /ucrt64/bin/epstopdf.exe
          ## Building core
          export PATH=/opt/codeblocks/bin:$PATH
          cd codeblocks_sfmirror/src/
          cp -rf ../../FortranProject ./plugins/contrib/
          cbp2make --config platform -unix
          cbp2make -in CodeBlocks_wx32.cbp -out Makefile_core
          sed '/zip -jq9*/ s/\\/\//g' Makefile_core -i
          sed -i '85 s/LIB_SDK = $(LIB) -lshfolder -ltxml -lwxscintilla_cb -lsquirrel -lgdi32/LIB_SDK = -lshfolder -ltxml -lwxscintilla_cb $(LIB) -lsquirrel -lgdi32/' Makefile_core
          sed 's/$(DEP_.*//g' Makefile_core -i
          export PATH=/opt/mingw32/bin:$PATH
          mingw32-make -f Makefile_core WX32_INCLUDE=/opt/wxwidgets3.2/include WX32_LIB=/opt/wxwidgets3.2/lib TARGET_OBJECT_DIR=.objs32

      - name: Display content of Makefiles
        shell: msys2 {0}
        run: |
          cd codeblocks_sfmirror/src/
          export PATH=/opt/codeblocks/bin:$PATH
          cbp2make -in ContribPlugins_wx32.workspace -out Makefile_plugins
          find -iname "*.mak" | while read line                                      
          do                                                                         
            sed -i '/zip -*/ s/\\/\//g' $line 
            sed -i 's/$(DEP_.*//g' $line
            sed -i '/cmd \/c "/ s/\//\\/g' $line
            sed -i 's/cmd \\c/cmd \/c/g' $line
            echo "---------------------------------"
            echo $line
            cat $line
            echo "---------------------------------"
          done

          sed -i '9,9 s/plugins_contrib_doxyblocks_doxyblocks_wx32//g' Makefile_plugins
          sed -i '9,9 s/plugins_contrib_source_exporter_exporter_wx32//g' Makefile_plugins
          sed -i '9,9 s/plugins_contrib_smartindent_smartindent_wx32//g' Makefile_plugins
          sed -i '9,9 s/plugins_contrib_clangd_client_clangd_client_wx32//g' Makefile_plugins
          sed -i '9,9 s/plugins_contrib_help_plugin_help_plugin_wx32//g' Makefile_plugins
          sed -i '9,9 s/plugins_contrib_spellchecker_spellchecker_wx32//g' Makefile_plugins
          sed -i '9,9 s/plugins_contrib_wxsmithcontribitems_wxsmithcontribitems_wx32//g' Makefile_plugins
          echo "---------------------------------"
          cat Makefile_plugins
          echo "---------------------------------"

      - name: Build plugins
        shell: msys2 {0}
        run: |
          cd codeblocks_sfmirror/src/
          export PATH=/opt/mingw32/bin:$PATH
          mingw32-make -f Makefile_plugins WX32_INCLUDE=/opt/wxwidgets3.2/include WX32_LIB=/opt/wxwidgets3.2/lib \
                                           TARGET_OBJECT_DIR=.objs32 MAKE=mingw32-make WX_VERSION=32 WX_SUFFIX=u \
                                           BOOST_INCLUDE=/opt/boost_1_86_0
        
      - uses: actions/upload-artifact@v4
        with:
          name: codeblocks32
          path: ${{ github.workspace }}\codeblocks_sfmirror\src\devel32
