name: main32

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW32
          location: D:\
          install: >-
            mingw-w64-i686-toolchain
            mingw-w64-i686-drmingw
            mingw-w64-i686-wxwidgets3.2-common-libs
            mingw-w64-i686-wxwidgets3.2-common
            mingw-w64-i686-wxwidgets3.2-msw
            mingw-w64-i686-wxwidgets3.2-msw-libs
            zip
            unzip
            git
            mingw-w64-i686-hunspell
            mingw-w64-i686-boost

      # Runs a set of commands using the runners shell
      - name: build32
        shell: msys2 {0}
        run: |
          wget -q https://github.com/zxunge/i686-codeblocks-builds/releases/download/r13542/codeblocks.zip
          unzip codeblocks.zip -d /opt/codeblocks/
          export PATH=$PATH:/opt/codeblocks/bin
          git clone https://github.com/arnholm/codeblocks_sfmirror.git
          cd codeblocks_sfmirror/src/
          codeblocks --batch-build-notify --no-batch-window-close --target=All --build CodeBlocks-unix.cbp
