name: main32

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW32
          location: D:\
          install: >-
            unzip
            p7zip
            git
            make

      - name: Prepare
        shell: msys2 {0}
        run: .ci/build.sh

      - name: build32
        shell: cmd
        run: |
          cd ${{ github.workspace }}\codeblocks_sfmirror\src\
          mingw32-make -f Makefile_core WX32_INCLUDE=D:/msys64/opt/wxwidgets3.2/include WX32_LIB=D:/msys64/opt/wxwidgets3.2/lib TARGET_OBJECT_DIR=.objs32
          
      - uses: actions/upload-artifact@v4
        with:
          name: codeblocks32
          path: ${{ github.workspace }}\codeblocks_sfmirror\src\devel32
