name: main32

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW32
          location: D:\
          install: >-
            zip
            unzip
            p7zip
            git
            mingw-w64-i686-boost

      # Runs a set of commands using the runners shell
      - name: build32
        shell: msys2 {0}
        run: |
          wget -q https://sourceforge.net/projects/codeblocks/files/Binaries/Nightlies/Prerequisites/Mingw64dlls14.1.0.7z
          wget -q https://sourceforge.net/projects/codeblocks/files/Binaries/Nightlies/Prerequisites/wxmsw32u_gcc_cb_wx325_2D_gcc1410-mingw64.7z
          7z x Mingw64dlls14.1.0.7z wxmsw32u_gcc_cb_wx325_2D_gcc1410-mingw64.7z -o/opt/codeblocks/bin
          export PATH=$PATH:/opt/codeblocks/bin
          git clone https://github.com/arnholm/codeblocks_sfmirror.git
          cd codeblocks_sfmirror/src/
          cbp2make -in CodeBlocks_wx32.cbp -out Makefile_core
      
      - uses: actions/upload-artifact@v4
        with:
          name: Makefile
          path: ${{ github.workspace }}\codeblocks_sfmirror\src\Makefile_core
